const students = [
    'Adam Kaufman-frey',
    'Alexander Brown',
    'Alexander Diaz',
    'Alexandrinov Silien',
    'Alondra Santana',
    'Amanda Changa',
    'Breanna Camacho',
    'Brian Zhen',
    'Charisse Ramsarran',
    'Corey Chamberlain',
    'David Barren',
    'Derick Hernandez',
    'Drew Andersen',
    'Eliot Cho',
    'Hamid Assaghli',
    'Heatherellen Strain',
    'Jack Rozovsky',
    'Jacob Robison',
    'James Parker',
    'Jordan Reeve',
    'Jose Muchati',
    'Justin McLaughlin',
    'Kayci Mercer',
    'Luis Lima',
    'Mark Norberte',
    'Melvin Urias',
    'Rawnaq Kabairzad',
    'Reina Simms',
    'Robert Green',
    'Sai Greeshma Shreya Yerragudi',
    'Setrige Crawford',
    'William Allred',
    'Xavier Leon',
]

